### ISSUE TITLE
Single json log to STDOUT

### ISSUE THREAD

**Issue by raivil** [reidmorrison/rails_semantic_logger#117]
### Environment

Provide at least:
* Ruby Version.
 2.7.0
* Rails Version.
 6.1
* Semantic Logger Version.
 4.7.4
* Rails Semantic Logger Version.
 4.4.6
* Other Application/framework names and versions (e.g. Puma, etc.).
Puma  5.1.1, sidekiq 6.1.2,pghero 2.7.3
* Rails configuration. Only need the settings related to Rails Semantic Logger and Semantic Logger.

```
  $stdout.sync = true
  config.rails_semantic_logger.add_file_appender = false
  config.rails_semantic_logger.format = :json
  config.semantic_logger.add_appender(io: $stdout, level: config.log_level, formatter: :json)
```

* Full Stack Trace, if an exception is being raised.
no stack

Note:
* Issues reported here should be related to monkey patches applied to Rails to make it use Semantic Logger. 
* For other logging and appender related issues, please report the issue at [Semantic Logger](https://github.com/rocketjob/semantic_logger/issues.

### Expected Behavior

My expectations is to have a unique JSON log entries on STDOUT without having to pass configurations to Puma.
Nonetheless, `quiet` mode is already default for Puma
```
-q, --quiet                      Do not log requests internally (default true)
```
Daemonizing puma/rails is not an option, since it executes as a single process in docker containers.

* Provide a standalone Ruby script or a link to an example repository that helps reproduce the issue.
* Use a basic application 

### Actual Behavior

* Describe or show the actual behavior.
Whenever running on development environment, application shows duplicated logs in two formats.
Simple example from a PgHero request
```
2021-01-07 18:18:26.251842 D [65732:puma threadpool 003] (14.3ms) ActiveRecord -- { :sql => "SHOW default_statistics_target /*pghero*/" }

{"host":"roguetwo.local","application":"Semantic Logger","environment":"development","timestamp":"2021-01-07T21:18:26.251842Z","level":"debug","level_index":1,"pid":65732,"thread":"puma threadpool 003","duration_ms":14.34500003233552,"duration":"14.3ms","name":"ActiveRecord","payload":{"sql":"SHOW default_statistics_target /*pghero*/"}}

```

**Comment by reidmorrison** [comment]
We run Puma using `bin/puma` and it does not log requests by default, we added the setting `log_requests` in `config/puma.rb` to turn that back on.

**Comment by ignisf** [comment]
@raivil, I believe this extension is the culprit:

https://github.com/rocketjob/rails_semantic_logger/blob/47112b2c9effe7ab72f4f99d46875ed8d67d0965/lib/rails_semantic_logger/extensions/rails/server.rb#L8

The workaround I've implemented is to clear all default appenders in an initializer and define my own. I am considering whether the introduction of a configuration variable similar to `config.rails_semantic_logger.add_file_appender` would be appropriate for tuning this behaviour. Maybe @reidmorrison could chime in here.

**Comment by reidmorrison** [comment]
Rails only call that method when you have logging to stdout turned on. If you turn it off, Rails will not call that method:
https://github.com/rails/rails/blob/663206d20aec374a28a24bb43bc7b1233042ed9b/railties/lib/rails/commands/server/server_command.rb#L42

**Comment by reidmorrison** [comment]
With Semantic Logger v4.8 you can now call `SemanticLogger.clear_appenders!` to remove all existing appenders, and then add just add the ones you want.
