### ISSUE TITLE
Question: how to disable colorized logging to file only?

### ISSUE THREAD

**Issue by leshik** [reidmorrison/rails_semantic_logger#140]
How to make it log in colors to stdout, but plain text to the `development.log` file? If I disable colorizing and specify the formatter, there's no color in both places:
```
  config.log_level = :debug
  config.colorize_logging = false
  config.semantic_logger.add_appender(io: $stdout, level: config.log_level, formatter: :color)
```

**Comment by leshik** [comment]
Further investigation shows that it's not possible to override the `formatter`. No matter what I put there, It's always either `:default` (which turns to `:color` unless `config.colorize_logging` is disabled), or anything else set globally with `config.rails_semantic_logger.format`. The `formatter` option inside `config.semantic_logger.add_appender` has no effect.

**Comment by leshik** [comment]
Turns out, [this line](https://github.com/reidmorrison/rails_semantic_logger/blob/v4.6.1/lib/rails_semantic_logger/engine.rb#L67) causes the problem, but I don't know how to better handle this situation.

**Comment by leshik** [comment]
Solved, there's a difference in logging behavior when launching the app via `rails s` vs `puma`. Rails adds IO logger already.

**Comment by dgmora** [comment]
@leshik This was long ago, but I'm facing the same issue. I've looked at the line you pointed out, but what did you do to make this work?

It looks to me like if you set  `config.colorize_logging = <true/false>` it's either both or none will use the color or not. As I see it now, this shouldn't be the case..?
