### ISSUE TITLE
Release 4.6.2 ? 

### ISSUE THREAD

**Issue by pre** [reidmorrison/rails_semantic_logger#142]
Any possibility to release 4.6.2 which would provide these changes? 

* https://github.com/reidmorrison/rails_semantic_logger/commit/6684880d013af1ddc47b7e16dffe61d4f60217d9
* https://github.com/reidmorrison/rails_semantic_logger/commit/7cf794fbb0f9b565bcc65f960e861e9fe69d30bf

Thanks!

**Comment by reidmorrison** [comment]
Great idea, `Successfully registered gem: rails_semantic_logger (4.6.2)`
