### ISSUE TITLE
URL in description is obsolete

### ISSUE THREAD

**Issue by nerixim** [reidmorrison/rails_semantic_logger#163]
Thanks for you work :shipit: 

The [URL](http://rocketjob.github.io/semantic_logger/rails.html) in repo description is invalid and you get a 404.
The [URL](https://logger.rocketjob.io/rails) in Readme seems to be the correct one 👍

**Comment by reidmorrison** [comment]
Thank you for letting me know @nerixim. Updated the incorrect url.
