### ISSUE TITLE
Not showing any logs in console

### ISSUE THREAD

**Issue by andresespinosapc** [reidmorrison/rails_semantic_logger#164]
### Environment

Provide at least:
* Ruby Version 2.7.5
* Rails Version 6.0
* Semantic Logger Version 4.11.0
* Rails Semantic Logger Version 4.10.0

### Expected Behavior

Logs are shown in the console in development.

### Actual Behavior

It doesn't show any logs, and don't know how to debug it.

**Comment by n-rodriguez** [comment]
https://logger.rocketjob.io/forking.html

**Comment by iamtekeste** [comment]
Although I updated my puma.rb I still don't see any of my logs.
How does one go about debugging this?

**Comment by reidmorrison** [comment]
By `console`, do you mean stdout, or inside a rails console?

**Comment by annaswims** [comment]
On https://logger.rocketjob.io/forking.html the documentation that says `If running Puma 2` should really say `If running Puma`. They're talking about any version >=2

**Comment by reidmorrison** [comment]
Thank you for the notes, also updated the documentation.
