### ISSUE TITLE
Deprecation warning with Rack 3

### ISSUE THREAD

**Issue by nickstanish** [reidmorrison/rails_semantic_logger#198]
### Environment

Provide at least:
* Ruby Version: 3.2.2
* Rails Version. 7-1-stable branch
* Semantic Logger Version: 4.14.0
* Rails Semantic Logger Version: 4.12.0 (though using this fix https://github.com/reidmorrison/rails_semantic_logger/pull/194)
* Other Application/framework names and versions (e.g. Puma, etc.). Rack 3.0.8
* Rails configuration. Only need the settings related to Rails Semantic Logger and Semantic Logger.
* Full Stack Trace, if an exception is being raised.

Note:
* Issues reported here should be related to monkey patches applied to Rails to make it use Semantic Logger. 
* For other logging and appender related issues, please report the issue at [Semantic Logger](https://github.com/reidmorrison/semantic_logger/issues.

### Expected Behavior

Deprecation warning is resolved

### Actual Behavior

Running `rails server` outputs a deprecation warning traced back to this line: https://github.com/reidmorrison/rails_semantic_logger/blob/f3aea8c8434a265a0a02c7a855552b14c6f39123/lib/rails_semantic_logger.rb#L61

```
Rack::Server is deprecated and replaced by Rackup::Server
=> Booting Puma
=> Rails 7.1.1 application starting in development
=> Run `bin/rails server --help` for more startup options
```

Rack 3 moved `Rack::Server` to `Rackup::Server`  https://github.com/rack/rackup/blob/eaea24a3d64a1b117df943a9d06779e659bb61af/lib/rack/server.rb#L6-L10

### Pull Request

* Consider submitting a Pull Request with a fix for the issue.
    * This is particularly helpful when running newer Rails versions, since we are not running it yet.
* Or, even a Pull request that only includes a test that reproduces the problem.

**Comment by reidmorrison** [comment]
A pull request would be most welcome.
