### ISSUE TITLE
missing v4.13.0 and v4.14.0 tags

### ISSUE THREAD

**Issue by znz** [reidmorrison/rails_semantic_logger#206]
fix url at <https://github.com/reidmorrison/rails_semantic_logger/commit/75ddc1607596f36c786fe863ccbd26b1a373969f>,
but <https://github.com/reidmorrison/rails_semantic_logger/tags> does not have v4.13.0 and v4.14.0.
So the link to Source Code in <https://rubygems.org/gems/rails_semantic_logger/versions/4.14.0> is broken.

**Comment by reidmorrison** [comment]
This happens because I use GitHub desktop and it does not push any tags that are created during the gem publish rake command. Will look into manually pushing those tags.

**Comment by reidmorrison** [comment]
Added the missing tags.
