### ISSUE TITLE
still seeing `Rack::Server is deprecated and replaced by Rackup::Server` warning

### ISSUE THREAD

**Issue by nov** [reidmorrison/rails_semantic_logger#211]
in my application, `rails_semantic_logger` gem is loaded before `rackup` gem is loaded.
it causes `Rack::Server is deprecated and replaced by Rackup::Server` warning.

to stop that warning, I had to specify `rackup` gem in my Gemfile.

**Comment by rgaufman** [comment]
Would be good to have this fixed, this is the only deprecation warning I have and I see it every time, seems like a simple fix to rename Rack::Server with Rackup::Server?

**Comment by krugerman007** [comment]
Any updates here? Please fix deprecation [🙏](https://emojipedia.org/folded-hands)

**Comment by dup2** [comment]
Would be nice to see this fixed!

**Comment by reidmorrison** [comment]
Let me know if you still see the warning after the PR was merged in `rails_semantic_logger` v 4.15.0.
