### ISSUE TITLE
Sidekiq jobs aren't Loggable with config.eager_load=true

### ISSUE THREAD

**Issue by jdelStrother** [reidmorrison/rails_semantic_logger#226]
Thanks for the recent sidekiq 7 support! I come bearing bugs:

### Environment

* Ruby Version: 3.2.4
* Rails Version: 7.1.3.4
* Semantic Logger Version: 4.15.0
* Rails Semantic Logger Version: 4.16.0
* Other Application/framework names and versions (e.g. Puma, etc.): Sidekiq 7.2.4
* Rails configuration:
   `config.eager_load = true` 

### Expected Behavior

SemanticLogger::Loggable is consistently included into Sidekiq::Job

### Actual Behavior

SemanticLogger::Loggable is included into Sidekiq::Job once RailsSemanticLogger's after_initialize hook has fired.
If Rails eager-loading is enabled, that means that all your sidekiq job classes get loaded (with the 'original' version of `Sidekiq::Job`), and _then_ RailsSemanticLogger mixes in Loggable - which is too late.

I've added a sample repo here:

https://github.com/jdelStrother/semantic-sidekiq

It [defines a SlowJob class](https://github.com/jdelStrother/semantic-sidekiq/blob/main/app/sidekiq/slow_job.rb) which uses Sidekiq::Job.

You can try using that logger with something like this in console:

<img width="541" alt="image" src="https://github.com/reidmorrison/rails_semantic_logger/assets/2377/b47b76f8-ec83-42e9-be73-e48436f8ee37">

which behaves as-expected.

However, if you enable eager loading:

<img width="590" alt="image" src="https://github.com/reidmorrison/rails_semantic_logger/assets/2377/3cb003c6-134c-43bc-8cba-767a504a8aee">

there's no `SlowJob.logger` class method. There's a logger instance method, but that's the regular `Sidekiq::Job#logger` method.

### Possible fix?

Maybe RailsSemanticLogger's `after_initialize` hook should instead be `initializer 'rails_semantic_logger', before: :eager_load!` ? Or the sidekiq patches could possibly be moved to a separate earlier hook (`before_initialize`) ? I'm not super-familiar with the Railtie initialization process, so don't take any of those as gospel.

**Comment by reidmorrison** [comment]
Worth giving Rails Semantic Logger v4.17.0 a try (release today), it moves the logger installation here:
https://github.com/reidmorrison/rails_semantic_logger/blob/6e1291f49c74f7241dbc9e92e28fbd60f8a1f37e/lib/rails_semantic_logger/engine.rb#L133

If not try pulling master and give your great options above a try to see if any resolve the class methods?

**Comment by jdelStrother** [comment]
Looks good! I've only tested locally, but it seems to fix this eager load issue.
