### ISSUE TITLE
undefined method `current_tags' for nil:NilClass

### ISSUE THREAD

**Issue by tmaier** [reidmorrison/rails_semantic_logger#232]
### Environment

* Ruby Version: `ruby 3.2.4 (2024-04-23 revision af471c0e01) [x86_64-linux]`
* Semantic Logger Version: `semantic_logger (4.16.0)`
* Application/framework names and versions (e.g. Rails, Sinatra, Puma, etc.). `rails (7.1.3.4)`
* Rails Semantic Logger Version, if applicable. `rails_semantic_logger (4.17.0)`
* Rails configuration. Only need the settings related to Rails Semantic Logger and Semantic Logger.
  ```ruby
    # Heroku compability & development mode
    if ENV['RAILS_LOG_TO_STDOUT'].present? || Rails.env.development?
      $stdout.sync = true
      config.semantic_logger.add_appender(io: $stdout, formatter: config.rails_semantic_logger.format)
    end

    # AppSignal integration
    appsignal_logger = Appsignal::Logger.new('rails', format: Appsignal::Logger::LOGFMT)
    config.semantic_logger.add_appender(logger: appsignal_logger, formatter: :logfmt)

    # Disable logging to a file
    config.rails_semantic_logger.add_file_appender = false

    # "info" includes generic and useful information about system operation, but avoids logging too much
    # information to avoid inadvertent exposure of personally identifiable information (PII). If you
    # want to log everything, set the level to "debug".
    config.log_level = ENV.fetch('RAILS_LOG_LEVEL', 'info').downcase.strip.to_sym

    # Prepend all log lines with the following tags.
    config.log_tags = {
      subdomain: :subdomain,
      request_id: :request_id
    }

    # Disable logging of assets
    config.rails_semantic_logger.quiet_assets = true
    
    config.solid_queue.logger = SemanticLogger['SolidQueue']
  ```
* Full Stack Trace, if an exception is being raised.
  ```text
  lib/active_job/logging.rb:32 logger_tagged_by_active_job?	
  lib/active_job/logging.rb:24 tag_logger	
  lib/active_job/logging.rb:14 block (2 levels) in <module:Logging>	
  lib/active_support/callbacks.rb:130 instance_exec	
  lib/active_support/callbacks.rb:130 block in run_callbacks	
  lib/active_support/callbacks.rb:141 run_callbacks	
  lib/active_job/enqueuing.rb:93 enqueue	
  lib/active_job/enqueuing.rb:60 perform_later	
  app/models/concerns/publication/searchable.rb:238 block in elasticsearch_index_async	
  ```
* I am using ActiveJob, SolidQueue gems
### Expected Behavior

I just wanted to call `IndexerJob.perform_later(operation.to_s, self.class.to_s, id)` successfully

ActiveJob::Logging has the following method:
```ruby
      def logger_tagged_by_active_job?
        logger.formatter.current_tags.include?("ActiveJob")
      end
```

This method expects a formatter to respond to `current_tags` method.

Source: https://github.com/rails/rails/blob/v7.1.3.4/activejob/lib/active_job/logging.rb

### Actual Behavior

Formatter is `nil` and thus, unable to respond to `current_tags` method.

```ruby
ApplicationJob.logger
#=> #<SemanticLogger::Logger:0x00007f3921c63070 @filter=nil, @level=nil, @level_index=nil, @name="Rails">
ApplicationJob.logger.formatter
#=> nil
```

### Similar Issues

The logstash-logger gem had a similar issue in 2017: https://github.com/dwbutler/logstash-logger/issues/112

### Pull Request

* Consider submitting a Pull Request with a fix for the issue.
    * This is particularly helpful when running newer Rails versions, since we are not running it yet.
* Or, even a Pull request that only includes a test that reproduces the problem.

**Comment by tmaier** [comment]
I found the issue. It was on my side.

**Comment by Startouf** [comment]
@tmaier I'm running into the same issue after a (bad) refactoring. What was the reason ?

I'm trying to plug semantic_logger as well, but without rails_semantic_logger
