### ISSUE TITLE
No logging output if rails server --daemon is used to start rails server

### ISSUE THREAD

**Issue by lightwave** [reidmorrison/rails_semantic_logger#69]
### Environment

* Ruby Version: 2.4.3p205
* Semantic Logger Version: 4.2.0
* Application/framework names: Rails 5.1.5
* Puma version: 3.11.3
* Rails Semantic Logger Version: 4.2.0
* Rails configuration. 

In config/application.rb:

```config.semantic_logger.backtrace_level = :trace```

In config/puma.rb

```
on_worker_boot do
  # Re-open appenders after forking the process
  SemanticLogger.reopen
end

```

### Expected Behavior

* I expect Rails server in daemon mode with --daemon should work the same.

### Actual Behavior

* If rails server --daemon is used to start the rails server, semantic will not output any loggings to log/development.log (or in production)

**Comment by lightwave** [comment]
Upgrading semantic_logger and rails_semantic_logger gems to 4.3.0 also have the same issue in daemon mode.

**Comment by lightwave** [comment]
Changing the web server to webrick still doesn't work. So, it's not puma that's causing the problem.

**Comment by lightwave** [comment]
Interestingly, if I do the following in one of the ActiveRecord, it'd cause the semantic logger to work in log/development.log. Note that the code below was opening the semantic logger to "/Users/chris/myclass.log".

```
def mylogger
  if !@mylogger
    SemanticLogger.default_level = :trace

    SemanticLogger.add_appender(file_name: '/Users/chris/myclass.log', formatter: :color)

    @logger = SemanticLogger['MyClass']
  end  
  @logger
end

def another_method
  mylogger.info "Hey it works now!"
end
```

Note that the message "Hey it works now!" will appears in both myclass.log and log/development.log". Since there is no tty attached to a daemon server, I still have no clue how to debug this.

**Comment by kolasss** [comment]
I have the same issue with a staging server (nginx-passenger)
Rails 5.1.5, rails_semantic_logger 4.3.0

**Comment by lightwave** [comment]
There are two differences in daemon process in Unix.

1. the process is detached from the tty
2. the working directory is changed to / by default.
3. by default, it'd close standard input, standard output, and standard error

That's how Rack (used by Rails) daemonize the rails server process.

I suspect that rails semantic logger was hooked to the standard output so that when standard output is closed, the logger's appender also got closed.

**Comment by lightwave** [comment]
A quick experiment verified that the problem is NOT due to chdir to / nor closing of the stdin/stdout/stderr when the rails/rack server process was daemonized. Ignore my previous comment.

**Comment by kolasss** [comment]
Very easy to reproduce:

1. `rails new app_name` with rails 5.2.0 (also tested with 5.1.5)
2. add `gem 'rails_semantic_logger'` to `Gemfile`
3. `bin/rails s --daemon`

**Comment by ddi-wtag** [comment]
Any updates on that one?

**Comment by we138-go** [comment]
`bin/rails s --daemon` detaches file descriptor from process and you need connect it again. I solved this way:

```
# lib/extensions/rack_extension.rb

module Extensions
  module RackExtension
    module Server
      def daemonize_app
        super
        SemanticLogger.reopen
      end
    end
  end
end

Rack::Server.prepend(Extensions::RackExtension::Server)
```

also, do remember `bin/rails s --daemon` changes current working directory to the root ('/'), so you must use absolute path to your logfile (if you are using file appenders)

```
config.semantic_logger.add_appender(
  file_name: Rails.root.join("log/#{Rails.env}.log"),
  level: config.log_level
)
```

@ddi-wtag @kolasss @lightwave

**Comment by we138** [comment]
`bin/rails s --daemon` detaches file descriptor from process and you need connect it again. I solved this way:

```
# lib/extensions/rack_extension.rb

module Extensions
  module RackExtension
    module Server
      def daemonize_app
        super
        SemanticLogger.reopen
      end
    end
  end
end

Rack::Server.prepend(Extensions::RackExtension::Server)
```

also, do remember `bin/rails s --daemon` changes current working directory to the root ('/'), so you must use absolute path to your logfile (if you are using file appenders)

```
config.semantic_logger.add_appender(
  file_name: Rails.root.join("log/#{Rails.env}.log"),
  level: config.log_level
)
```

@ddi-wtag @kolasss @lightwave

**Comment by reidmorrison** [comment]
Thank you @we138 that is certainly not an expected behavior. Thankfully we use `bin/puma` so have not had to deal with the `--daemon` issue above.
