### ISSUE TITLE
SQL Output no longer appears in local dev Rails console

### ISSUE THREAD

**Issue by hpjaj** [reidmorrison/rails_semantic_logger#83]
### Environment

* Ruby Version - 2.3.0
* Rails Version - 4.2.11
* Semantic Logger Version - 4.2.2
* Rails Semantic Logger Version - 4.2.1
* Other Application/framework names and versions (e.g. Puma, etc.) - puma 3.12.0
* Settings related to Rails Semantic Logger and Semantic Logger:

```ruby
# config/environments/development.rb  

config.rails_semantic_logger.semantic   = false
config.rails_semantic_logger.started    = true
config.rails_semantic_logger.processing = true
config.rails_semantic_logger.rendered   = true
```

```ruby
# config/environments/production.rb  

config.rails_semantic_logger.format = :json
config.rails_semantic_logger.add_file_appender = false
config.semantic_logger.add_appender(io: STDOUT,
                                    level: config.log_level,
                                    formatter: config.rails_semantic_logger.format)

config.semantic_logger.application = if Sidekiq.server?
                                       'vets-api-worker'
                                     else
                                       'vets-api-server'
                                     end
```

### Expected Behavior

In a traditional Rails app, in the local dev Rails console we get SQL output when executing commands.  This gives us insight into what SQL is being called, in order to make queries more performant, and mitigate against any regression.

For example:

```ruby
irb(main):001:0> Account.last
  Account Load (1.0ms)  SELECT  "accounts".* FROM "accounts"  ORDER BY "accounts"."id" DESC LIMIT 1
=> #<Account id: 1684, uuid: "12345678-3eb0-4bd5-8913-95df7c615be8", idme_uuid: "12345678604dd4a12aa67609a63b22", icn: "101
```

### Actual Behavior

Once we added the `rails_semantic_logger` gem, the SQL output in the local dev Rails console **no longer outputs**.  For example:

```ruby
irb(main):001:0> Account.last
=> #<Account id: 1684, uuid: "12345678-3eb0-4bd5-8913-95df7c615be8", idme_uuid: "12345678604dd4a12aa67609a63b22", icn: "1012740600V714187", edipi: "1234568910115", created_at: "2018-12-19 20:30:19", updated_at: "2018-12-19 20:30:19">
```

### Attempt to fix

If we add this to `config/environments/development.rb`

```ruby
# config/environments/development.rb  

config.semantic_logger.add_appender(
  io: STDOUT,
  level: :debug,
  formatter: config.rails_semantic_logger.format
)
```

two things happen.

1. It brings back the default SQL output in the local dev Rails console
2. It **duplicates** every log message in the Rails server logs:

```
2019-01-07 15:26:10.676464 I [27537:puma 001] [[]] Rails -- Started GET "/v0/status" for ::1 at 2019-01-07 15:26:10 -0700
2019-01-07 15:26:10.676464 I [27537:puma 001] [[]] Rails -- Started GET "/v0/status" for ::1 at 2019-01-07 15:26:10 -0700
2019-01-07 15:26:10.783202 I [27537:puma 001] [[]] V0::AdminController -- Processing #status
2019-01-07 15:26:10.783202 I [27537:puma 001] [[]] V0::AdminController -- Processing #status
2019-01-07 15:26:10.817942 I [27537:puma 001] [[]] Rails -- Rendered ActiveModel::Serializer::Null with Hash (0.22ms)
2019-01-07 15:26:10.817942 I [27537:puma 001] [[]] Rails -- Rendered ActiveModel::Serializer::Null with Hash (0.22ms)
2019-01-07 15:26:10.818304 I [27537:puma 001] [[]] Rails -- Completed 200 OK in 35ms (Views: 33.8ms | ActiveRecord: 0.0ms)
2019-01-07 15:26:10.818304 I [27537:puma 001] [[]] Rails -- Completed 200 OK in 35ms (Views: 33.8ms | ActiveRecord: 0.0ms)
2019-01-07 15:26:10.818713 I [27537:puma 001] [[]] Rails -- [StatsD] increment api.rack.request:1 #controller:v0/admin #action:status #status:200
2019-01-07 15:26:10.818713 I [27537:puma 001] [[]] Rails -- [StatsD] increment api.rack.request:1 #controller:v0/admin #action:status #status:200
2019-01-07 15:26:10.818753 I [27537:puma 001] [[]] Rails -- [StatsD] measure api.rack.request.duration:88.517 #controller:v0/admin #action:status
2019-01-07 15:26:10.818753 I [27537:puma 001] [[]] Rails -- [StatsD] measure api.rack.request.duration:88.517 #controller:v0/admin #action:status
```

So that fix will not work, unless there is other Semantic logging config we can add in to remove the duplication?

That said, ideally we are hoping this is a bug, and there is a straightforward way to bring back the SQL output.

**Comment by reidmorrison** [comment]
In order to add this feature, suggest looking into how Rails itself is logging the SQL to stdout, but only when running in a console.
It is not so much a logging entry, but some special case output that Rails must be doing under the covers. My guess is they hacked the LogSubscriber for SQL logging to make it write to stdout when inside a rails console. By adding that same code to the following LogSubscriber it should work:
https://github.com/rocketjob/rails_semantic_logger/blob/master/lib/rails_semantic_logger/active_record/log_subscriber.rb

We add `.to_sql` to the end of any query to make it display the SQL it would use. However, adding the above behavior will be awesome, especially for newer developers.

**Comment by sumeetattree** [comment]
Running into the same issue. Is it possible to disable semantic logger just for the console? I would be content with the default logger printing sql logs.

**Comment by reidmorrison** [comment]
I found the following code inside `active_record/railtie.rb`:
~~~ruby
console do |app|
      require "active_record/railties/console_sandbox" if app.sandbox?
      require "active_record/base"
      unless ActiveSupport::Logger.logger_outputs_to?(Rails.logger, STDERR, STDOUT)
        console = ActiveSupport::Logger.new(STDERR)
        console.level = Rails.logger.level
        Rails.logger.extend ActiveSupport::Logger.broadcast console
      end
      ActiveRecord::Base.verbose_query_logs = false
    end
~~~

It appears that _all_ logging is echoed to stderr, not just sql queries.

For anyone running windows without Semantic Logger, is that what it does?

If so, it would be simple to add a stderror logger to semantic logger every time a console is started. Is that what we want? I.e. Echo all log output to stderror when running inside a console?
