### ISSUE TITLE
Would this be easy to adapt to supporting CEE? (Common event expression, e.g JSON over Syslog)

### ISSUE THREAD

**Issue by cultureulterior** [reidmorrison/rails_semantic_logger#9]

**Comment by reidmorrison** [comment]
Should not be hard at all to modify the Syslog appender to send JSON over Syslog. Is there an open source server we can test against that uses this format?
Including @marc since he wrote the Syslog appender for Semantic Logger

**Comment by cultureulterior** [comment]
Rsyslog supports it for input and output now

**Comment by reidmorrison** [comment]
Have you considered adding this support and submitting a pull request?

It should not be difficult to use the existing syslog appender and then just replace the formatter with your own that then sends JSON formatted messages.

Looking forward to a pull request with CEE syslog support.
